on: pull_request

name: CI

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install prerequisites
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -Dwarnings -Dclippy::all -Dclippy::pedantic

      - name: Run Rustfmt
        run: cargo fmt --check

      - name: Run tests
        run: cargo test

      - name: Build for Linux
        run: |
          cargo build --release
          tar -C target/release/ -cf target/release/smart-garden-gateway-boot-analyzer.tar smart-garden-gateway-boot-analyzer

      - name: Archive Linux binary
        uses: actions/upload-artifact@v3
        with:
          name: smart-garden-gateway-boot-analyzer-linux
          path: target/release/smart-garden-gateway-boot-analyzer.tar

      - name: Install prerequisites for Windows build
        run: |
          sudo apt-get install -y g++-mingw-w64-x86-64
          rustup target add x86_64-pc-windows-gnu

      - name: Build for Windows
        run: cargo build --target x86_64-pc-windows-gnu --release

      - name: Archive Windows binary
        uses: actions/upload-artifact@v3
        with:
          name: smart-garden-gateway-boot-analyzer-windows
          path: target/x86_64-pc-windows-gnu/release/smart-garden-gateway-boot-analyzer.exe
